### ISSUE TITLE
using core.Resource in a Dart transformer leads to Build error

### ISSUE THREAD

**Issue by sethladd** [dart-lang/barback#65]
_From @simon-void on September 19, 2015 16:15_

using the core.Resource class in a Barback transformer leads to a build error in the project referencing that transformer. In case of my [transformer project](https://github.com/simon-void/simple_resource_loading_transformer/blob/master/lib/transformer.dart) this error looks like this:
_Build error: Transform InsertCopyright on {your project} threw error: Load Error for "package:simple_resource_loading_transformer/copyright.txt": SocketException: OS Error: Connection refused_
a little bit more explanation in this [stackoverflow ticket](http://stackoverflow.com/questions/32660355/using-core-resource-in-a-dart-transformer-leads-to-build-error)

_Copied from original issue: dart-lang/sdk#24382_

**Comment by nex3** [comment]
Can you post a minimal reproduction repo?

**Comment by simon-void** [comment]
you can link to my simple_resource_loading_transformer:

```
dependencies:
  simple_resource_loading_transformer:
    git: https://github.com/simon-void/simple_resource_loading_transformer.git

transformers:
- simple_resource_loading_transformer
```

or do you mean i should create such a minimal project that uses this transformer?
